apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: delivereats
data:
  NODE_ENV: production
  PORT: "3000"
  AUTH_SERVICE_URL: auth-service:50052
  CATALOG_SERVICE_URL: catalog-service:50051
  ORDER_SERVICE_URL: order-service:50053
  DELIVERY_SERVICE_URL: delivery-service:50054
  FX_SERVICE_URL: fx-service:50056
  PAYMENT_SERVICE_URL: payment-service:50057
  CORS_ORIGIN: http://frontend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: delivereats
spec:
  replicas: 2  # Alta disponibilidad para el gateway
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: delivereats/api-gateway:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-gateway-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: delivereats
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: delivereats
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"  # Para soportar fotos base64
spec:
  ingressClassName: nginx
  rules:
    - host: api.delivereats.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 3000
